import Head from "next/head";
import PostBordered from "../components/PostBordered";
// import Posts from "../components/Posts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PostBordered />
      </main>
    </div>
  );
}
